version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5555:5432'

volumes:
  database-data:
