version: '3.8'
services:
  mongodb-challenge:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb-data:/var/lib/mongodb/data/
    ports:
      - '27017:27017'

volumes:
  mongodb-data:
